"""fleet.toml -> what Flux applies in each cluster (clusters/<name>/) and the kind lab configs (kind/).

clusters/<name>/
  flux-system/sync.yaml   GitRepository + three Flux Kustomizations (applied once by scripts/up.sh)
  operators/              HelmRepository and HelmReleases: GPU Operator, Network Operator
  config/                 one NVIDIADriver and one NicNodePolicy per node pool
  lifecycle/              repo 11's rollout controller, its lab node agent and the rollout plan
"""

from __future__ import annotations

from . import plan as planmod
from .config import Cluster, Fleet, Release

HEADER = "# Generated by `python -m fleet render` from fleet.toml. Do not edit: change fleet.toml.\n"
LIFECYCLE_NS = "gpu-lifecycle"
AGENT_NS = "gpu-node-agent"


def _ns(name: str, privileged: bool = False) -> dict:
    meta: dict = {"name": name}
    if privileged:
        meta["labels"] = {"pod-security.kubernetes.io/enforce": "privileged"}
    return {"apiVersion": "v1", "kind": "Namespace", "metadata": meta}


def major_minor(chart_version: str) -> tuple[int, int]:
    a, b = chart_version.lstrip("v").split(".")[:2]
    return int(a), int(b)


# ---- operators ----------------------------------------------------------------------------------

def gpu_operator_values(rel: Release) -> dict:
    return {
        "operator": {"upgradeCRD": False},   # Flux replaces the CRDs (install/upgrade crds: CreateReplace)
        "driver": {
            "enabled": True,
            # one NVIDIADriver per node pool (config/) instead of one driver for the whole cluster
            "nvidiaDriverCRD": {"enabled": True, "deployDefaultCR": False},
            # nodes are upgraded one by one by the rollout controller (lifecycle/), not by the operator
            "upgradePolicy": {"autoUpgrade": False},
        },
    }


def network_operator_values(rel: Release) -> dict:
    return {
        "upgradeCRDs": False,                     # same: Flux replaces the CRDs
        # one Node Feature Discovery per cluster: the GPU Operator's. The rules that label NVIDIA NICs
        # are still deployed by this chart.
        "nfd": {"enabled": False, "deployNodeFeatureRules": True},
    }


def helm_release(name: str, namespace: str, version: str, values: dict, depends: list | None = None) -> dict:
    spec: dict = {
        "interval": "10m",
        "timeout": "10m",
        "chart": {"spec": {"chart": name, "version": version,
                           "sourceRef": {"kind": "HelmRepository", "name": "nvidia", "namespace": "flux-system"}}},
        "install": {"crds": "CreateReplace", "remediation": {"retries": 2}},
        "upgrade": {"crds": "CreateReplace", "remediation": {"retries": 2}},
        "values": values,
    }
    if depends:
        spec["dependsOn"] = depends
    return {"apiVersion": "helm.toolkit.fluxcd.io/v2", "kind": "HelmRelease",
            "metadata": {"name": name, "namespace": namespace}, "spec": spec}


def operators(f: Fleet, c: Cluster) -> dict[str, list[dict]]:
    rel = f.platform(c)
    return {
        "namespaces.yaml": [_ns("gpu-operator", True), _ns("nvidia-network-operator", True)],
        "helmrepository.yaml": [{
            "apiVersion": "source.toolkit.fluxcd.io/v1", "kind": "HelmRepository",
            "metadata": {"name": "nvidia", "namespace": "flux-system"},
            "spec": {"interval": "1h", "url": f.helm_repository},
        }],
        "gpu-operator.yaml": [helm_release("gpu-operator", "gpu-operator", rel.gpu_operator,
                                           gpu_operator_values(rel))],
        "network-operator.yaml": [helm_release("network-operator", "nvidia-network-operator", rel.network_operator,
                                               network_operator_values(rel),
                                               [{"name": "gpu-operator", "namespace": "gpu-operator"}])],
    }


# ---- per node pool --------------------------------------------------------------------------------

def nvidia_driver(f: Fleet, c: Cluster, pool) -> dict:
    """The CRD changed between GPU Operator versions: v26.7 requires `default` and moved the upgrade
    policy into the CR. The fields follow the operator version the cluster runs."""
    plat = f.platform(c)
    spec: dict = {
        "driverType": "gpu",
        "repository": "nvcr.io/nvidia",
        "image": "driver",
        "version": f.release(pool.release).driver,
        "nodeSelector": {planmod.POOL_LABEL: pool.name},
    }
    if major_minor(plat.gpu_operator) >= (26, 7):
        spec["default"] = False
        spec["upgradePolicy"] = {"autoUpgrade": False}
    return {"apiVersion": "nvidia.com/v1alpha1", "kind": "NVIDIADriver",
            "metadata": {"name": pool.name, "labels": {"fleet.lab/release": pool.release}}, "spec": spec}


def nic_node_policy(f: Fleet, c: Cluster, pool) -> dict:
    return {
        "apiVersion": "mellanox.com/v1alpha1", "kind": "NicNodePolicy",
        "metadata": {"name": pool.name, "labels": {"fleet.lab/release": pool.release}},
        "spec": {
            "nodeSelector": {planmod.POOL_LABEL: pool.name},
            "ofedDriver": {"image": "doca-driver", "repository": "nvcr.io/nvidia/mellanox",
                           "version": f.release(pool.release).doca,
                           "upgradePolicy": {"autoUpgrade": False}},
        },
    }


def config(f: Fleet, c: Cluster) -> dict[str, list[dict]]:
    return {
        "nvidiadrivers.yaml": [nvidia_driver(f, c, p) for p in c.pools],
        "nicnodepolicies.yaml": [nic_node_policy(f, c, p) for p in c.pools],
    }


# ---- repo 11: rollout controller, lab node agent, plan -------------------------------------------

def lifecycle(f: Fleet, c: Cluster) -> dict[str, list[dict]]:
    lc = f.lifecycle
    sec = {"allowPrivilegeEscalation": False, "readOnlyRootFilesystem": True, "capabilities": {"drop": ["ALL"]}}
    pod_sec = {"runAsNonRoot": True, "seccompProfile": {"type": "RuntimeDefault"}}
    rbac = [
        {"apiVersion": "v1", "kind": "ServiceAccount", "metadata": {"name": "gpu-lifecycle", "namespace": LIFECYCLE_NS}},
        {"apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRole", "metadata": {"name": "gpu-lifecycle"},
         "rules": [
             {"apiGroups": [""], "resources": ["nodes"], "verbs": ["get", "list", "patch"]},
             {"apiGroups": [""], "resources": ["pods"], "verbs": ["list"]},
             {"apiGroups": [""], "resources": ["pods/eviction"], "verbs": ["create"]},
             {"apiGroups": [""], "resources": ["events"], "verbs": ["create"]},
         ]},
        {"apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRoleBinding", "metadata": {"name": "gpu-lifecycle"},
         "roleRef": {"apiGroup": "rbac.authorization.k8s.io", "kind": "ClusterRole", "name": "gpu-lifecycle"},
         "subjects": [{"kind": "ServiceAccount", "name": "gpu-lifecycle", "namespace": LIFECYCLE_NS}]},
        {"apiVersion": "rbac.authorization.k8s.io/v1", "kind": "Role",
         "metadata": {"name": "gpu-lifecycle", "namespace": LIFECYCLE_NS},
         "rules": [
             {"apiGroups": [""], "resources": ["configmaps"], "verbs": ["get", "create", "patch"]},
             {"apiGroups": ["batch"], "resources": ["jobs"], "verbs": ["create", "get", "delete"]},
         ]},
        {"apiVersion": "rbac.authorization.k8s.io/v1", "kind": "RoleBinding",
         "metadata": {"name": "gpu-lifecycle", "namespace": LIFECYCLE_NS},
         "roleRef": {"apiGroup": "rbac.authorization.k8s.io", "kind": "Role", "name": "gpu-lifecycle"},
         "subjects": [{"kind": "ServiceAccount", "name": "gpu-lifecycle", "namespace": LIFECYCLE_NS}]},
    ]
    controller = {
        "apiVersion": "apps/v1", "kind": "Deployment",
        "metadata": {"name": "gpu-lifecycle", "namespace": LIFECYCLE_NS,
                     "annotations": {"fleet.lab/source": f"{lc.repo}/tree/{lc.commit}"}},
        "spec": {
            "replicas": 1, "strategy": {"type": "Recreate"},
            "selector": {"matchLabels": {"app.kubernetes.io/name": "gpu-lifecycle"}},
            "template": {
                "metadata": {"labels": {"app.kubernetes.io/name": "gpu-lifecycle"}},
                "spec": {
                    "serviceAccountName": "gpu-lifecycle",
                    "nodeSelector": {"node-role.kubernetes.io/control-plane": ""},
                    "tolerations": [{"key": "node-role.kubernetes.io/control-plane", "effect": "NoSchedule"}],
                    "securityContext": pod_sec,
                    "containers": [{
                        "name": "controller", "image": lc.image, "imagePullPolicy": "IfNotPresent",
                        "command": ["/usr/local/bin/gpulifecycle"],
                        "args": ["-interval=3s", f"-validation-image={lc.validation_image}", "-agent-port=9500"],
                        "env": [{"name": "POD_NAMESPACE", "valueFrom": {"fieldRef": {"fieldPath": "metadata.namespace"}}}],
                        "ports": [{"name": "metrics", "containerPort": 8080}],
                        "livenessProbe": {"httpGet": {"path": "/healthz", "port": "metrics"}, "periodSeconds": 20},
                        "resources": {"requests": {"cpu": "20m", "memory": "32Mi"}, "limits": {"memory": "64Mi"}},
                        "securityContext": sec,
                    }],
                },
            },
        },
    }
    agent = {
        "apiVersion": "apps/v1", "kind": "DaemonSet",
        "metadata": {"name": "node-agent", "namespace": AGENT_NS},
        "spec": {
            "selector": {"matchLabels": {"app.kubernetes.io/name": "node-agent"}},
            "template": {
                "metadata": {"labels": {"app.kubernetes.io/name": "node-agent"}},
                "spec": {
                    "hostNetwork": True,
                    "nodeSelector": {planmod.GPU_LABEL: "true"},
                    "tolerations": [{"operator": "Exists"}],
                    "automountServiceAccountToken": False,
                    "securityContext": pod_sec,
                    "containers": [{
                        "name": "agent", "image": lc.image, "imagePullPolicy": "IfNotPresent",
                        "command": ["/usr/local/bin/node-agent"],
                        # the version every lab node starts with; later versions only come from rollouts
                        "args": ["-listen=:9500", f"-version={f.releases[0].driver}", "-install-delay=3s",
                                 f"-bad-versions={','.join(lc.bad_versions)}"],
                        "env": [{"name": "NODE_NAME", "valueFrom": {"fieldRef": {"fieldPath": "spec.nodeName"}}}],
                        "readinessProbe": {"httpGet": {"path": "/healthz", "port": 9500}},
                        "resources": {"requests": {"cpu": "10m", "memory": "16Mi"}, "limits": {"memory": "32Mi"}},
                        "securityContext": sec,
                    }],
                },
            },
        },
    }
    plan_cm = {"apiVersion": "v1", "kind": "ConfigMap",
               "metadata": {"name": "rollout-plan", "namespace": LIFECYCLE_NS},
               "data": planmod.configmap_data(f, c)}
    return {
        "namespaces.yaml": [_ns(LIFECYCLE_NS), _ns(AGENT_NS, True)],
        "controller.yaml": rbac + [controller],
        "node-agent.yaml": [agent],
        "rollout-plan.yaml": [plan_cm],
    }


# ---- Flux sync and kind --------------------------------------------------------------------------

# The lab Git server (a Gitea container on the kind network). scripts/up.sh swaps the host name for the
# container's IP when it applies sync.yaml, so it does not depend on DNS for containers.
GIT_URL = "http://fleet-git:3000/fleet/fleet.git"


def sync(c: Cluster) -> dict[str, list[dict]]:
    src = {"kind": "GitRepository", "name": "fleet"}

    def ks(name: str, wait: bool, depends: list[str] | None = None) -> dict:
        spec: dict = {"interval": "1m", "retryInterval": "20s", "timeout": "15m", "path": f"./clusters/{c.name}/{name}",
                      "prune": True, "wait": wait, "sourceRef": src}
        if depends:
            spec["dependsOn"] = [{"name": d} for d in depends]
        return {"apiVersion": "kustomize.toolkit.fluxcd.io/v1", "kind": "Kustomization",
                "metadata": {"name": name, "namespace": "flux-system"}, "spec": spec}

    return {"sync.yaml": [
        {"apiVersion": "source.toolkit.fluxcd.io/v1", "kind": "GitRepository",
         "metadata": {"name": "fleet", "namespace": "flux-system"},
         "spec": {"interval": "30s", "url": GIT_URL, "ref": {"branch": "main"}}},
        ks("operators", True),
        ks("config", False, ["operators"]),   # the CRDs come with the operators
        ks("lifecycle", True),
    ]}


def kind(c: Cluster) -> dict:
    nodes: list[dict] = [{"role": "control-plane"}]
    for p in c.pools:
        for _ in range(p.nodes):
            nodes.append({"role": "worker", "labels": {planmod.POOL_LABEL: p.name, planmod.GPU_LABEL: "true"}})
    return {"kind": "Cluster", "apiVersion": "kind.x-k8s.io/v1alpha4", "name": c.name, "nodes": nodes}


def files(f: Fleet) -> dict[str, list[dict]]:
    """Every generated file, path -> documents."""
    out: dict[str, list[dict]] = {}
    for c in f.clusters:
        for sub, fn in (("flux-system", lambda c: sync(c)), ("operators", lambda c: operators(f, c)),
                        ("config", lambda c: config(f, c)), ("lifecycle", lambda c: lifecycle(f, c))):
            for name, docs in fn(c).items():
                out[f"clusters/{c.name}/{sub}/{name}"] = docs
        out[f"kind/{c.name}.yaml"] = [kind(c)]
    return out
